# Generated by Django 5.1 on 2024-09-03 16:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancel_cause_choice', models.CharField(blank=True, choices=[('c1', 'Причина1'), ('c2', 'Причина2'), ('c3', 'Причина3')], max_length=2, null=True)),
                ('cancel_cause', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('fr', 'Свободно'), ('re', 'Забронировано')], default='fr', max_length=2)),
                ('start_time', models.TimeField()),
                ('duration', models.IntegerField(blank=True, default=60)),
                ('context', models.TextField(blank=True, null=True)),
                ('appointments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultations.appointment')),
                ('reserved_for_user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('work_shift_start_time', models.TimeField()),
                ('work_shift_end_time', models.TimeField()),
                ('slots', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='consultations.slot')),
            ],
        ),
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speciality', models.TextField()),
                ('is_on_vacation', models.BooleanField(blank=True, default=False)),
                ('schedules', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='consultations.schedule')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
