# Generated by Django 5.1 on 2024-09-08 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='slots',
        ),
        migrations.RemoveField(
            model_name='slot',
            name='appointments',
        ),
        migrations.RemoveField(
            model_name='specialist',
            name='schedules',
        ),
        migrations.AddField(
            model_name='appointment',
            name='slot',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='consultations.slot'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='specialist',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='consultations.specialist'),
        ),
        migrations.AddField(
            model_name='slot',
            name='schedule',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='consultations.schedule'),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='speciality',
            field=models.CharField(),
        ),
    ]
