# Generated by Django 5.1 on 2024-09-11 09:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0002_remove_schedule_slots_remove_slot_appointments_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='slot',
            options={'ordering': ['-start_time']},
        ),
        migrations.AlterModelOptions(
            name='specialist',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='appointment',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='consultations.slot'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='specialist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='consultations.specialist'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='reserved_for_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='slot',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='consultations.schedule'),
        ),
    ]
